[TrainData.CityScapes]
data_path = 'xxx'
!transforms = ['RandomResize', 'RandomFlip', 'Normalize']


[RandomResize]
prob = 0.5

[Transform.RandomFlip]
prob = 0.5
axis = 0

[Normalize]
std = [0.5, 0.5, 0.5]
mean = [0.5, 0.5, 0.5]
