repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.4
  hooks:
    - id: ruff
      types_or: [python, pyi, jupyter]
      args: [--fix]
    - id: ruff-format
      types_or: [python, pyi, jupyter]
