size = 1024

[TrainData.CityScapes]
&img_size = "size"
!transforms = ['RandomResize', 'RandomFlip', 'Normalize', 'Pad']
data_path = 'xxx'


# 如果使用默认参数不在配置文件中声明也可以, 仍然会build RandomResize
# [RandomResize]

[Transform.RandomFlip]
prob = 0.5
axis = 0

[Transform.Pad]
&pad_size = "size"

[Normalize]
std = [0.5, 0.5, 0.5]
mean = [0.5, 0.5, 0.5]

[TestData.CityScapes]
!transforms = ['Normalize']
&img_size = "size"
data_path = 'xxx'
