[TrainData.CityScapes]
data_path = 'xxx'
!transforms = ['RandomResize', 'RandomFlip', 'Normalize', 'Pad']


# 如果使用默认参数不在配置文件中声明也可以, 仍然会build RandomResize
# [RandomResize]

[Transform.RandomFlip]
prob = 0.5
axis = 0

[Transform.Pad]

[Normalize]
std = [0.5, 0.5, 0.5]
mean = [0.5, 0.5, 0.5]

[TestData.CityScapes]
data_path = 'xxx'
!transforms = ['Normalize']
