[Model.FCN]
@backbone = 'ResNet'
!head1 = 'SimpleHead'
@head2 = 'SimpleHead'
# It's formal to use quoted keys instead of a bare key, but whatever.
# "!head1" = 'SimpleHead'

[Model.SimpleHead]
in_channel = 256
num_classes = 80

[Backbone.ResNet]
!block = "BasicBlock"
in_channel = 3
depth = 50
layers = [1, 2, 3, 4]

[BasicBlock]
in_chan = 3
out_chan = 4


[SimpleHead]
in_channel = 256
num_classes = 19
