[Model.FCN]
@backbone = 'ResNet'
# It's formal to use quoted keys instead of a bare key, but whatever.
# "@head" = 'SimpleHead'
@head = 'SimpleHead'

[Backbone.ResNet]
$block = "BasicBlock"
in_channel = 3
depth = 50
layers = [1, 2, 3, 4]

[Model.SimpleHead]
$timer = "time"
in_channel = 256
num_classes = 19
