[Optimizer.AdamW]
# both methods can work
# @params = "FCN.parameters()" 
@params = "$Model.parameters()"
weight_decay = 0.01

[LRSche.CosDecay]
@optimizer='AdamW'
learning_rate = 0.1

[Loss.CrossEntropyLoss]
[Loss.OHEM]
[Loss.BoundaryLoss]
