[Optimizer.AdamW]
# both methods can work
# @params = "FCN.parameters()@ParamsArgHook"
# `$Model` represents get module from field `Model`
# `.parameters()` represents invoke the method `parameters`
# `@ParamsArgHook` represents a post-hook for the result of `$Model.parameters()`
@params = "$Model.parameters()@$ConfigHook::ParamsArgHook@$Scratchpads::ParamsArgHook@DoSomething"
weight_decay = 0.01

[ConfigHook.ParamsArgHook]
enabled = true

[Scratchpads.ParamsArgHook]
enabled = true

[LRSche.CosDecay]
@optimizer='AdamW'
learning_rate = 0.1

[Loss.CrossEntropyLoss]
[Loss.OHEM]
[Loss.BoundaryLoss]
