name: CodeStyle Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    name: CodeStyle Check ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run codestyle-check
        run: |
          pip install pre-commit==3.5.0
          pre-commit install
          pre-commit run
