name: CodeStyle Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    name: CodeStyle Check ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run codestyle-check
        run: |
          uv run pre-commit install
          uv run pre-commit run
