
name: example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Test example
        run: |
          cd ./example
          poetry run python init.py
          poetry run python run.py
