name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: uv sync --dev

      - name: Initialize ExCore
        run: |
          cd ./tests
          export EXCORE_DEBUG=1
          uv run python init.py

      - name: Test with pytest
        run: |
          cd ./tests
          uv run pytest --cov=../excore
          uv run python init.py
          uv run pytest test_config.py
          uv run pytest test_config.py
          uv run pytest test_config.py
          uv run pytest test_config.py

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
